name: Build package
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: echo "::set-output name=version::$(grep 'pkgver=' PKGBUILD | awk -F "=" '{print $2}')"
        id: version
      - name: Build archlinux package
        run: |
          docker build -t arch-builder .
          docker run --rm -v "${PWD}:/opt/build" arch-builder
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: '*.zst'
