name: Build package
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build archlinux package
        uses: mijailr/arch-makepkg-action@1.0.1
      - name: See whats done
        run: |
          ls -l .
