name: Build package
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: echo "::set-output name=version::$(grep 'pkgver=' PKGBUILD | awk -F "=" '{print $2}')"
        id: version
      - name: Build archlinux package
        run: |
          docker build -t arch-builder .
          docker run --rm -v "${PWD}:/opt/build" arch-builder
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.version.outputs.version }}"
          title: v${{ steps.version.outputs.version }}
          prerelease: false
          files: |
            *.zst
